name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              export DB_PORT=5432 && export DB_USER=${{ secrets.DB_USER }} && export DB_HOST=${{ secrets.DB_HOST }} && export DB_PASSWORD=${{ secrets.DB_PASSWORD }} && export DB_PORT=${{ secrets.DB_PORT }}
              env > variables.txt
              cd /home/proyecto_db
              git pull
              pip install -r requirements.txt
              python3 manage.py makemigrations
              python3 manage.py migrate
              gunicorn shop.wsgi:application --bind 0.0.0.0:8000
              '
